# Alpine Linux Unattended Installation Answerfile

KEYMAPOPTS="us us"
HOSTNAMEOPTS="-n docker-vm"
INTERFACESOPTS="auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp"
TIMEZONEOPTS="-z UTC"
PROXYOPTS="none"
# The -c flag adds the community repo, which is needed for docker-compose
APKREPOSOPTS="-c"
SSHDOPTS="-c openssh"
NTPOPTS="-c chrony"
DISKOPTS="-m sys /dev/sda"
